/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import React, { forwardRef } from 'react'

import { Center, useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    bunny: THREE.Mesh
  }
  materials: {
    ['Default OBJ']: THREE.MeshStandardMaterial
  }
}

const Bunny = forwardRef<THREE.Group, GroupProps>(function Bunny(props, ref) {
  const { nodes } = useGLTF(
    'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/bunny/model.gltf',
  ) as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <Center>
        <mesh geometry={nodes.bunny.geometry} scale={[0.6, 0.6, 0.6]}>
          {props.children}
        </mesh>
      </Center>
    </group>
  )
})

useGLTF.preload(
  'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/bunny/model.gltf',
)

export default Bunny
