/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import React, { forwardRef } from 'react'

import { Center, useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    marble_bust_01: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

const Mug = forwardRef<THREE.Group, GroupProps>(function Mug(props, ref) {
  const { nodes } = useGLTF('marble_bust_01_1k.gltf') as GLTFResult

  return (
    <group ref={ref} {...props} dispose={null}>
      <Center>
        <mesh scale={[4, 4, 4]} geometry={nodes.marble_bust_01.geometry}>
          {props.children}
        </mesh>
      </Center>
    </group>
  )
})

useGLTF.preload(
  'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/mug/model.gltf',
)

export default Mug
